input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    accel_profile = flat

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

